### ISSUE TITLE
Not importing the template in Zabbix version 4

### ISSUE THREAD

**Issue by rodrigodecosta** [azatuni/zabbix-nginx-stats#1]
I could not import this template into version 4 of zabbix, the malformed xml error

**Comment by azatuni** [comment]
Hi, 
this templates was tested on zabbix 3.0, will test on zabbix 4.0 and update you

**Comment by azatuni** [comment]
Hi,

imported template on version Zabbix 4.0.3, no any problems found

BR,
Areg
